#!/bin/sh
sudo apt-get install libudev-dev
sudo apt-get install libnss3-1d=3.12.8-1+squeeze4
sudo apt-get install libxml2=2.7.8.dfsg-2+squeeze3
sudo apt-get install libkrb5support0=1.8.3+dfsg-4squeeze5
sudo apt-get install libkrb5-3=1.8.3+dfsg-4squeeze5 libk5crypto3=1.8.3+dfsg-4squeeze5 libgssapi-krb5-2=1.8.3+dfsg-4squeeze5 
sudo apt-get install bison fakeroot flex g++ g++-multilib gperf \
		 libapache2-mod-php5 libasound2-dev libbz2-dev libcairo2-dev \
		 libdbus-glib-1-dev libgconf2-dev libgl1-mesa-dev libglu1-mesa-dev \
		 libglib2.0-dev libgtk2.0-dev libjpeg62-dev libnspr4-dev libnss3-dev \
		 libpam0g-dev libsqlite3-dev libxslt1-dev libxss-dev \
		 mesa-common-dev patch perl pkg-config python \
		 python2.5-dev rpm subversion libcupsys2-dev libgnome-keyring-dev \
		 libcurl4-gnutls-dev libelf-dev \
		 #libbluetooth-dev

